FROM node:22-slim AS build
WORKDIR /docs
COPY package*.json ./
RUN npm ci --ignore-scripts
COPY docs ./docs
RUN npm run docs:build
FROM nginx:stable-alpine
COPY --from=build /docs/docs/_build /usr/share/nginx/html
EXPOSE 80
