# frozen_string_literal: true

require 'rspec'
require_relative 'docs_provider_assets'

RSpec.describe DocsProviderAssets do
  around do |example|
    Dir.mktmpdir('paygen-docs-spec-') do |directory|
      @directory = directory
      example.run
    end
  end

  it 'copies exact generated bytes, binds all generator inputs and is repeatable across directories' do
    first = File.join(@directory, 'first')
    second = File.join(@directory, 'second')
    FileUtils.mkdir_p([first, second])
    manifest = described_class.build(first)
    expect(described_class.build(second)).to eq(manifest)
    project = Paygen::Project.init(File.join(described_class::ROOT, 'fixtures/novapay/openapi.yaml'),
                                  output: File.join(@directory, 'independent'),
                                  profile: File.join(described_class::ROOT, 'fixtures/novapay/integration.yml'))
    Paygen::Generator.new(project).generate
    described_class::FILES.each do |name|
      expect(File.binread(File.join(first, 'downloads/novapay', name))).to eq(File.binread(project.path("generated/#{name}")))
    end
    expect(manifest.fetch('generated_input_sha256')).to eq(project.lock.fetch('inputs'))
    expect(manifest.fetch('generated_input_sha256').keys).to include('integration.yml', 'recipes/selected.yml')
  end

  it 'refuses an existing publication instead of overwriting it' do
    described_class.build(@directory)
    expect { described_class.build(@directory) }.to raise_error(/already exists/)
  end

  it 'refuses a symlinked downloads parent without writing outside the output' do
    outside = File.join(@directory, 'outside')
    output = File.join(@directory, 'site')
    FileUtils.mkdir_p([outside, output])
    File.symlink(outside, File.join(output, 'downloads'))
    expect { described_class.build(output) }.to raise_error(/symbolic-link/)
    expect(Dir.children(outside)).to be_empty
  end

  it 'rejects an identity that does not match the checkout' do
    allow(ENV).to receive(:[]).and_call_original
    allow(ENV).to receive(:[]).with('PAYGEN_SOURCE_SHA').and_return('0' * 40)
    expect { described_class.source_sha }.to raise_error(/does not match/)
  end
end
