# frozen_string_literal: true
require 'open3'
require 'rbconfig'

module Paygen
  class Generator
    attr_reader :project
    def initialize(project)
      @project = project.is_a?(Project) ? project : Project.new(project)
    end

    def render(draft: false, overrides: {})
      ir = project.ir(overrides: overrides)
      blockers = ir.diagnostics.select { |item| item['severity'] == 'blocker' }
      if blockers.any? && !draft
        raise Error.new('Resolve semantic blockers before generation', code: 'SEMANTIC_BLOCKERS', exit_code: 4,
                        details: { 'diagnostics' => blockers })
      end
      config = ir.config
      config['draft'] = true if draft && blockers.any?
      files = {
        'config.json' => Paygen.json(config),
        'INTEGRATION.md' => guide(ir),
        'fixtures.json' => Paygen.json(fixtures(ir)),
        'provenance.json' => Paygen.json(ir.provenance),
        'diagnostics.json' => Paygen.json({ 'diagnostics' => ir.diagnostics })
      }
      if blockers.empty?
        files["#{ir.profile.fetch('provider')}_service.rb"] = service(config)
      end
      files
    end

    def generate(draft: false, overrides: {})
      drift = project.generated_drift
      unless drift.empty?
        raise Error.new('Generated files have changed; preserve your edits before regenerating', code: 'GENERATED_DRIFT', exit_code: 1, details: { 'files' => drift })
      end
      files = render(draft: draft, overrides: overrides)
      files.each do |name, body|
        next unless name.end_with?('.rb')
        _out, _err, status = Open3.capture3(RbConfig.ruby, '-c', stdin_data: body)
        raise Error.new('Generated Ruby failed syntax validation', code: 'GENERATOR_ERROR', exit_code: 70) unless status.success?
      end
      previous = project.lock.fetch('generated', {})
      files.each { |name, body| project.write("generated/#{name}", body) }
      (previous.keys - files.keys).each { |name| File.delete(project.path("generated/#{name}")) }
      lock = { 'version' => 1, 'paygen_version' => VERSION, 'inputs' => project.input_hashes,
               'generated' => files.to_h { |name, body| [name, Digest::SHA256.hexdigest(body)] },
               'overrides' => overrides, 'draft' => draft }
      project.write('paygen.lock', Paygen.json(lock))
      { 'status' => 'generated', 'files' => files.keys.sort, 'draft' => draft }
    end

    def diff
      expected = render(draft: project.lock.fetch('draft', false), overrides: project.lock.fetch('overrides', {}))
      tracked = project.lock.fetch('generated', {})
      (expected.keys | tracked.keys).sort.filter_map do |name|
        target = project.path("generated/#{name}")
        current = File.file?(target) ? File.read(target) : nil
        next if current == expected[name]
        { 'path' => name, 'change' => current.nil? ? 'add' : (expected[name].nil? ? 'remove' : 'change') }
      end + project.generated_drift.select { |item| item['reason'] == 'untracked' }
    end

    def export(output:)
      changes = diff
      raise Error.new('Regenerate before exporting', code: 'GENERATED_DRIFT', exit_code: 1) unless changes.empty?
      destination = File.expand_path(output)
      raise Error, 'Export destination already exists' if File.exist?(destination)
      raise Error, 'Export destination cannot be inside the project' if destination.start_with?(project.root + '/')
      FileUtils.mkdir_p(destination)
      Dir[project.path('generated/*')].each { |file| FileUtils.cp(file, destination) if File.file?(file) }
      runtime_source = File.expand_path('runtime', __dir__)
      FileUtils.mkdir_p(File.join(destination, 'lib/paygen'))
      FileUtils.cp_r(runtime_source, File.join(destination, 'lib/paygen/runtime'))
      File.write(File.join(destination, 'Gemfile'), "source 'https://rubygems.org'\ngem 'json_schemer', '~> 2.4'\ngem 'bigdecimal', '>= 3.1'\ngem 'rack', '~> 3.1'\n")
      File.write(File.join(destination, 'DETACHED.md'), "# Detached integration\n\nThis export is user-owned and is not safely regenerable. Install dependencies with bundle install. Add this directory's lib to RUBYLIB and load your Provider::BaseService before the service. Review credentials and hook contract in INTEGRATION.md.\n")
      { 'status' => 'exported', 'path' => destination, 'detached' => true }
    end

    private

    def service(config)
      <<~RUBY
        # frozen_string_literal: true
        # Generated by Paygen #{VERSION}. Change integration.yml or extensions, then regenerate.
        require 'json'
        require 'paygen/runtime/adapter'
        class Provider::#{config.fetch('class_name')} < Provider::BaseService
          PAYGEN_CONFIG = JSON.parse(#{JSON.generate(config).dump}).freeze
          include Paygen::Runtime::Adapter
        end
      RUBY
    end

    def guide(ir)
      config = ir.config
      lines = ["# #{ir.document.dig('info', 'title')} integration", '',
               'Generated from the pinned OpenAPI contract, ordered overlays and integration.yml.', '',
               '## Setup', '', 'Load Provider::BaseService, require the generated service and call configure_paygen with your credentials and transport.',
               'Credentials are supplied at runtime. Never store API keys or callback secrets in profiles or generated files.',
               'The reference harness describes the backend seam; validate it against your real backend before deployment.', '',
               '## Operations', '', '| Role | Method | Path |', '| --- | --- | --- |']
      config.fetch('endpoints').each { |role, op| lines << "| #{cell(role)} | #{op['method']} | #{cell(op['path'])} |" }
      lines += ['', '## Status mapping', '', '| Provider | Canonical |', '| --- | --- |']
      config.fetch('status_mapping', {}).each { |provider, state| lines << "| #{cell(provider)} | #{cell(state)} |" }
      lines += ['', '## Authentication and amounts', '',
                "Authentication: `#{cell(config.dig('auth', 'type') || 'none')}`; credential values stay outside generated source.",
                "Amount scale: `#{config.dig('amount', 'scale')}`. Minimum provider units: `#{config.dig('amount', 'minimum')}`.",
                'Use decimal strings or integers for monetary input. Floating point money is rejected.', '',
                '## Webhooks and retries', '',
                'Pass the exact request bytes through raw_body and the received headers to process_callback.',
                'Configure callback_secret at runtime, or the configured rotation credential names. Validate identity, replay handling and terminal-state transitions in your application.',
                'Reuse the same operation identity and idempotency key after timeout. A timeout may mean the provider committed the payout; reconcile before retrying.',
                'Unknown statuses do not approve operations. Batch success does not imply every item succeeded.', '',
                '## Errors', '', '| HTTP | Classification | Action |', '| --- | --- | --- |']
      config.fetch('errors', {}).each { |code, rule| lines << "| #{cell(code)} | #{cell(rule.is_a?(Hash) ? rule['code'] : rule)} | #{cell(rule.is_a?(Hash) ? rule['action'] : '')} |" }
      lines += ['', '## Extensions', '',
                'User-owned Ruby files live in extensions/. Load them explicitly in your application after loading the generated service.',
                'Hooks: paygen_validate, paygen_request, paygen_response, paygen_status, paygen_verify_callback, paygen_classify_error and paygen_retry_decision.',
                'Review hook signatures in lib/paygen/runtime/adapter.rb. YAML is declarative and cannot execute Ruby.', '',
                '## Provenance', '', 'See provenance.json for the winning source of each semantic fact; config.json contains the effective configuration.', '']
      lines.join("\n")
    end

    def fixtures(ir)
      ir.config.fetch('endpoints').to_h do |role, operation|
        examples = operation.fetch('request_examples', {})
        request = examples['example'] || examples.fetch('examples', {}).values.first&.fetch('value', nil) || schema_example(operation.fetch('request_schema', {}))
        responses = operation.fetch('responses', {}).to_h do |status, response|
          content = response.fetch('content', {}).values.first || {}
          example = content['example'] || content.fetch('examples', {}).values.first&.fetch('value', nil) || schema_example(content.fetch('schema', {}))
          ["response_#{status}", example]
        end
        [role, { 'request' => request }.merge(responses)]
      end
    end

    def schema_example(schema, depth = 0)
      return nil if depth > 16
      return schema['example'] if schema.key?('example')
      return schema['default'] if schema.key?('default')
      return schema['enum'].first if schema['enum'].is_a?(Array)
      if schema['properties']
        schema['properties'].to_h { |key, value| [key, schema_example(value, depth + 1)] }.compact
      elsif schema['type'] == 'array'
        []
      elsif schema['type'] == 'boolean'
        false
      elsif %w[number integer].include?(schema['type'])
        schema.fetch('minimum', 0)
      end
    end

    def cell(value)
      value.to_s.gsub('|', '\\|').gsub(/[\r\n]/, ' ')
    end
  end
end
