# frozen_string_literal: true
require 'tempfile'

module Paygen
  module Runtime
    # Loads already-verified generated bytes in an isolated Provider namespace.
    # Applications retain ownership of their actual BaseService implementation.
    module ReferenceProvider
      def self.load_service(source:, class_name:)
        sandbox = Module.new
        provider = Module.new
        base = Class.new do
          def initialize(**configuration)
            configure_paygen(**configuration)
          end
        end
        provider.const_set(:BaseService, base)
        sandbox.const_set(:Provider, provider)
        Tempfile.create(['paygen-verified-', '.rb']) do |file|
          file.write(source)
          file.flush
          Kernel.load(file.path, sandbox)
        end
        provider.const_get(class_name, false)
      end
    end
  end
end
