# frozen_string_literal: true
require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec) do |task|
  task.pattern = File.expand_path('spec/**/*_spec.rb', __dir__)
  task.rspec_opts = ['--options', File.expand_path('.rspec', __dir__), '-I', File.expand_path('spec', __dir__)]
end
task default: :spec
